set(VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION ${VERSION})
set(CPACK_GENERATOR "RPM")
install(
        PROGRAMS "${CMAKE_CURRENT_BINARY_DIR}/antarctica"
        DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
)
set(CPACK_PACKAGE_NAME "antarctica")
set(CPACK_PACKAGE_RELEASE 1)
set(CPACK_PACKAGE_CONTACT "Nikita Mironov")
set(CPACK_PACKAGE_VENDOR "Mad Penguins")
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")
include(CPack)